sudo: false

language: go

go:
  - 1.4.3
  - 1.5.3

install:
  - go get -t -d -v ./...
  - go get golang.org/x/tools/cmd/cover

services:
  - redis-server

script:
  - go test -v -cover .
  - go test -v -cover ./apiserver
